### ISSUE TITLE
Several surfaces result in "index out of range"

### ISSUE THREAD

**Issue by MadsPJ** [ladybug-tools/honeybee-plus#50] opened 2017-04-26 09:30 UTC
Hello,

I have used faces as an input for honeybee surfaces. Whenever I just have one surface as an input everything works, but if I input a list of surfaces I get an "index out of range" error. 

The input for the Honeybee surface should be "A single surface or a list of surfaces" so I do not understand what I am doing wrong. 

If i remove the flatten node then i get an error saying:
"Failed to extract points! 'List [object]' object has no attribute"

![index out of range](https://cloud.githubusercontent.com/assets/26253323/25427507/11f5228c-2a73-11e7-94c8-492c73da8653.JPG)

**Comment by mostaphaRoudsari** [comment] 2017-05-03 13:20
@MadsPJ I can't recreate this error. Can you share a simple example file? Thanks.

**Comment by MadsPJ** [comment] 2017-05-14 19:52
Hello mostaphaRoudsari,

Will this be enough to see whats wrong?

[DF error.zip](https://github.com/ladybug-tools/honeybee-plus/files/999678/DF.error.zip)

Is the selection of faces a bad method for defining which surfaces to import?

**Comment by mostaphaRoudsari** [comment] 2017-05-17 15:29
@MadsPJ thanks for sharing the file. I will check soon and get back to you! Selection faces should be as good as any other methods.

**Comment by mostaphaRoudsari** [comment] 2017-05-27 15:34
@MadsPJ Thank you for the file. I can recreate the error. I'll report back shortly.

**Comment by mostaphaRoudsari** [comment] 2017-05-27 15:57
@MadsPJ the error was happening because of a single name and multiple surfaces. I was catching the wrong exception in the code. A temporary solution is to disconnect the name input. I will push a fix soon.

**Comment by mostaphaRoudsari** [comment] 2017-05-27 21:20
This is fixed in the new release version 1.1

**Closed by mostaphaRoudsari** 2017-05-27 21:20 UTC
Labels: bug, dynamo

**Comment by MadsPJ** [comment] 2017-05-29 06:53
Super. Thank you very much.

**Comment by samykbs** [comment] 2017-09-06 16:54
Hi everyone:

Thanks for all the hardwork you have been doing for honeybee and lady bug for the last update realese in dynamo.

Ive been learning more about the radiance subject, im not sure is this is a bug or im doing something wrong, ive been trying to figure it out, but no luck. 

HBZones never seems to work when i plug to HBobjets to run the analysis, what im doing is convert the geometry to Honeybee-surfaces but for some reason it is only working with a few surface, and this is happening with every sample file i'm running for the radiance analysis. 

After this if I checked "true" to run the analysis i get an error related to line 41 in the script, anyway ill keep practicing and reading about this.

Hope this feedback is helpful for the community and if anyone knows what the issue is ill apreciate some help.

Thanks 


![analysis flatten list](https://user-images.githubusercontent.com/17571612/30123212-dca17ab2-92f6-11e7-92d4-8e6e7ded4fab.png)
![analysis](https://user-images.githubusercontent.com/17571612/30123216-ded329b6-92f6-11e7-8aec-a137a620e975.png)
![analysis geometry](https://user-images.githubusercontent.com/17571612/30123475-b3c7faca-92f7-11e7-9e2e-050e3123378d.PNG)
![analysis error](https://user-images.githubusercontent.com/17571612/30124082-b74a605a-92f9-11e7-849c-b90b35a9f59c.png)

**Comment by mostaphaRoudsari** [comment] 2017-09-07 00:42
Hi @samykbs, Thank you for the feedback. I'm not clear about the issue. Can you open a new issue and share the example files so I can recreate the problem?
